- type: job
  id: AggressiveAnimals
  name: job-name-aggressive-animals
  playTimeTracker: AntahAggressiveAnimals
  setPreference: false
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 20h

- type: job
  id: SpaceDragon
  name: job-name-space-dragon
  description: job-description-space-dragon
  playTimeTracker: AntagSpaceDragon
  setPreference: false
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 20h



