- type: department
  id: Law
  name: department-Law
  sort: 0
  description: department-law-description
  color: "#323ba9"
  roles:
  - Magistrate
  - IAA
  - Lawyer
  primary: false
  weight: 80

- type: department
  id: RedWings
  name: department-RedWings
  description: department-redwings-description
  color: "#772026" #ss220-chatcolor
  roles:
  - RedWingsOfficer
  - RedWingsMedic
  - RedWingsPilot
  editorHidden: true
  weight: 90
  lightColor: "#902922"