- type: job
  id: RedWingsPilot
  name: ghost-role-information-redwings-pilot-name
  description: ghost-role-information-redwings-pilot-description
  playTimeTracker: JobRedWingsPilot
  canBeAntag: false
  icon: JobIconRedWingsPilot
  setPreference: false
  overrideConsoleVisibility: true
  access:
  - Medical
  - Brig
  - Maintenance
  - External
  - Interdyne