- type: job
  id: RedWingsMedic
  name: job-name-redwings-medic
  description: job-description-redwings-medic
  playTimeTracker: JobRedWingsMedic
  canBeAntag: false
  icon: JobIconRedWingsMedic
  setPreference: false
  overrideConsoleVisibility: true
  access:
  - Medical
  - Brig
  - Maintenance
  - External
