- type: job
  id: RedWingsOfficer
  name: job-name-redwings-officer
  description: job-description-redwings-officer
  playTimeTracker: JobGhostRole
  canBeAntag: false
  icon: JobIconRedWingsOfficer
  setPreference: false
  overrideConsoleVisibility: true
  access:
  - Medical
  - Brig
  - Maintenance
  - External
  - Interdyne
