- type: startingGear
  id: VisitorTourist
  equipment:
    jumpsuit: ClothingUniformRandomShirt
    shoes: ClothingShoesColorYellow
    head: ClothingHeadHatYellowsoft
    id: VisitorPDA
    back: ClothingBackpack
    ears: ClothingHeadsetGrey
    eyes: ClothingEyesGlassesSunglasses
    pocket1: TapeRecorder
    pocket2: CassetteTape

- type: startingGear
  id: VisitorTouristAlt
  equipment:
    jumpsuit: ClothingUniformRandomStandard
    shoes: ClothingShoesColorGreen
    head: ClothingHeadHatGreensoft
    id: VisitorPDA
    back: ClothingBackpack
    ears: ClothingHeadsetGrey
    pocket1: TapeRecorder
    pocket2: CassetteTape

- type: startingGear
  id: RedWingsOfficerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitMilitaryFeldsher
    back: ClothingBackpackSecurity
    shoes: ClothingShoesBootsCombatFilled
    eyes: ClothingEyesGlassesBallistic
    mask: ClothingMaskNeckGaiter
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitRedWingsSec
    suitstorage: WeaponLaserSMG
    id: RedWingsSecurityPDA
    ears: ClothingHeadsetRedWings
    belt: ClothingBeltSecurity
    pocket1: DoubleEmergencyOxygenTankFilled
    pocket2: WeaponDisabler
  storage:
    belt: 
    - Stunbaton
    - LaserSMGPowerCell
    - LaserSMGPowerCell
    - LaserSMGPowerCell 
    - GrenadeFlashBang
    - TearGasGrenade
    - Zipties
    - Zipties
    back:
    - BoxSurvivalBrigmedic
    - CrowbarRed
    - MedkitCombatFilled
    - RedWingsClientPaper
    - PinpointerDNA

- type: startingGear
  id: RedWingsMedicGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitMilitaryFeldsher
    back: ClothingBackpackSatchelBrigmedic
    shoes: ClothingShoesBootsCombatFilled
    eyes: ClothingEyesHudSyndChem
    mask: ClothingMaskNeckGaiterRed
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitRedWingsMedic
    suitstorage: WeaponLaserSMG
    id: RedWingsMedicPDA
    ears: ClothingHeadsetRedWings
    belt: ClothingBeltSecurityMedical
    pocket1: DoubleEmergencyOxygenTankFilled
    pocket2: WeaponDisabler
  storage:
    belt: 
    - MedicatedSuture
    - RegenerativeMesh
    - CombatMedipen
    - CombatMedipen
    - PunctAutoInjector
    - PyraAutoInjector
    - AirlossAutoInjector
    - AntiPoisonMedipen
    back:
    - BoxSurvivalBrigmedic
    - CrowbarRed
    - MedkitCombatFilled
    - PinpointerDNA
    - LaserSMGPowerCell
    - LaserSMGPowerCell
    - DefibrillatorSyndicate
    - EmergencyRollerBedSpawnFolded
    - RedWingsClientPaper

- type: startingGear
  id: RedWingsPilotGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitMilitaryFeldsher
    back: ClothingBackpackSecurity
    shoes: ClothingShoesBootsCombatFilled
    eyes: ClothingEyesGlassesBallistic
    mask: ClothingMaskNeckGaiter
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitRedWingsPilot
    suitstorage: WeaponDisablerSMG
    id: RedWingsPilotPDA
    ears: ClothingHeadsetRedWings
    belt: ClothingBeltSecurity
    pocket1: DoubleEmergencyOxygenTankFilled
    pocket2: WeaponPistolViper
  storage:
    belt: 
    - Stunbaton
    - Zipties
    - Zipties
    - Zipties
    - Zipties
    - Flash
    - MagazinePistol
    - MagazinePistolRubber
    - MagazinePistolRubber
    back:
    - BoxSurvivalBrigmedic
    - CrowbarRed
    - MedkitCombatFilled
    - HandHeldMassScanner
    - RedWingsClientPaper
    - PinpointerDNA
